In [10]:
from sklearn.datasets import fetch_openml
#https://www.openml.org/d/37
#Pima Indians Diabetes Database
diabetes = fetch_openml(name='diabetes',  as_frame=True)
print(diabetes.frame.columns)
print(diabetes.frame.describe())
print(diabetes.details)



Index(['preg', 'plas', 'pres', 'skin', 'insu', 'mass', 'pedi', 'age', 'class'], dtype='object')
             preg        plas        pres        skin        insu        mass  \
count  768.000000  768.000000  768.000000  768.000000  768.000000  768.000000   
mean     3.845052  120.894531   69.105469   20.536458   79.799479   31.992578   
std      3.369578   31.972618   19.355807   15.952218  115.244002    7.884160   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000   99.000000   62.000000    0.000000    0.000000   27.300000   
50%      3.000000  117.000000   72.000000   23.000000   30.500000   32.000000   
75%      6.000000  140.250000   80.000000   32.000000  127.250000   36.600000   
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000   

             pedi         age  
count  768.000000  768.000000  
mean     0.471876   33.240885  
std      0.331329   11.760232  
min      0.078000   21.000000  
25%      0.243

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:301: UserWarning: Multiple active versions of the dataset matching the name diabetes exist. Versions may be fundamentally different, returning version 1.
  warn(
/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [11]:
#Get rid of any rown with NA's
diabetes.frame = diabetes.frame.dropna()

In [14]:
#from sklearn.datasets import fetch_openml
#load mice protein dataset from OpenML
#mice = fetch_openml(name='miceprotein', version=4, as_frame=True)
#list(mice.frame.columns)
#print(mice.details)
#mice.frame.describe()


# Import required libraries
import numpy as np
import sklearn
from sklearn.neural_network import MLPClassifier


# Import model to divide data into training and testing sets
from sklearn.model_selection import train_test_split


#import onehotencoder
from sklearn.preprocessing import OneHotEncoder


target_column = ['class']
#dropping target column for onehot encoding
predictorsdroptarget = diabetes.frame.drop(columns=target_column)
# Apply OneHotEncoder to categorical variables
encoder = OneHotEncoder(drop='first', sparse=False)
# fit and transoformed data
predictors = encoder.fit_transform(predictorsdroptarget)
print(predictors)





[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [19]:
#the input data
X = predictors
#the output data
y = diabetes.frame['class']

#we encode target classes from strings to numbers as neural networks cannot require all numerical inputs and outputs
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

#divide data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)
print(X_train.shape); print(X_test.shape)

from sklearn import svm

svm_model = svm.SVC(decision_function_shape='ovo')
svm_model.fit(X_train, y_train)

#We predict the training set
predict_train = svm_model.predict(X_train)
#we predict the test set
predict_test = svm_model.predict(X_test)

from sklearn.metrics import classification_report,confusion_matrix

print('Training accuracy')
#we report the confusion matrix for the training set
print(confusion_matrix(y_train,predict_train))
#we report various accuracy statistics for the training set
print(classification_report(y_train,predict_train))

print('Testing accuracy')
#we report the confusion matrix for the test set
print(confusion_matrix(y_test,predict_test))
#we report various accuracy statistics for the test set
print(classification_report(y_test,predict_test))



(537, 1246)
(231, 1246)
Training accuracy
[[338   0]
 [ 14 185]]
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       338
           1       1.00      0.93      0.96       199

    accuracy                           0.97       537
   macro avg       0.98      0.96      0.97       537
weighted avg       0.97      0.97      0.97       537

Testing accuracy
[[156   6]
 [ 61   8]]
              precision    recall  f1-score   support

           0       0.72      0.96      0.82       162
           1       0.57      0.12      0.19        69

    accuracy                           0.71       231
   macro avg       0.65      0.54      0.51       231
weighted avg       0.67      0.71      0.63       231

